---
### DataBase MariaDB
- name: Add MariaDB Repository
  yum_repository:
    name: MariaDB
    description: MariaDB
    file: MariaDB.repo
    baseurl: http://yum.mariadb.org/10.4/centos7-amd64
    gpgcheck: true
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    enabled: true 

- name: install mysql (mariadb)
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server
    - MySQL-python
    - libsemanage-python
    - policycoreutils
    - checkpolicy
  
- name: enable mysql (mariadb)
  systemd:
    name: mariadb
    state: restarted
    enabled: yes

- name: 'mysql_root_password'
  mysql_user:
    login_user: root
    login_password: "{{ mysql_password }}"
    user: root
    check_implicit_admin: true
    password: "{{ mysql_password }}"
    host: localhost
  no_log: true  

- name: 'root password'
  blockinfile:
    path: ~/.my.cnf
    create: yes
    block: |
      [client]
      user=root
      password={{ mysql_password }}      

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
  no_log: true   

- name: test database is absent
  mysql_db:
    name: test
    state: absent    

- name: create mysql zabbix user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_password }}"
    name: "zabbix"
    password: 'zabbix'
    priv: 'zabbix.*:ALL,GRANT'
    state: present
  no_log: true  

- name: Create database for Zabbix
  mysql_db:
    name: zabbix
    encoding: utf8
    collation: utf8_bin  
    state: present    

- name: Restore Zabbix database
  mysql_db:
    name: zabbix
    state: import
    target: /vagrant/provision/roles/zabbix/files/zabbix.sql.gz

### Zabbix Server

- name: install the Zabbix repo
  yum:
    name: http://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present

- name: yum-clean-all
  command: yum clean all
  args:
    warn: no  

- name: Install Zabbix Server and Agent
  yum:
    name: "{{ item }}"
    state: present    
  loop:
    - zabbix-server-mysql
    - zabbix-agent

- name: Install  Red Hat Software Collections
  yum:
    name: centos-release-scl
    state: present     


- name: 'Enable Zabbix frontend repo'
  ini_file: dest=/etc/yum.repos.d/zabbix.repo
    section="zabbix-frontend"
    option=enabled
    value=1    

- name: Install Zabbix Web
  yum:
    name: "{{ item }}"
    state: present    
  loop:
    - zabbix-web-mysql-scl
    - zabbix-apache-conf-scl


- name: 'Config Zabbix'
  lineinfile:
    path:  "{{ item.path }}" 
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { path: '/etc/zabbix/zabbix_server.conf', regexp: '^# DBPassword=', line: 'DBPassword=zabbix'} 
    - { path: '/etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf', regexp: '^; php_value[date.timezone] = Europe/Riga', line: 'php_value[date.timezone] = Europe/Moscow'}
  notify:
    - restart zabbix
    - restart mysql


- name: Set Sebool for Zabbix
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes    

- name: Set Sebool for Zabbix
  seboolean:
    name: httpd_can_connect_zabbix 
    state: yes
    persistent: yes  

- name: Set Sebool for Zabbix
  seboolean:
    name: zabbix_can_network 
    state: yes
    persistent: yes 
  notify:
    - restart zabbix    

- name: "SELinux | RedHat | Add SEmodule to fix SELinux issue: zabbix_server_alerter.sock"
  script:
    cmd: files/install_semodule.bsx
  args:
    creates: /etc/selinux/targeted/active/modules/400/zabbix_server_add/cil
    become: yes                          


### Firewall Settings 

- name: Firewalld service - firewalld is running
  systemd:
    name: firewalld
    enabled: true
    state: started  

- firewalld:
    service: zabbix-server
    permanent: true
    state: enabled 

- firewalld:
    service: zabbix-agent
    permanent: true
    state: enabled 

- firewalld:
    service: http
    permanent: true
    state: enabled 

- firewalld:
    service: https
    permanent: true
    state: enabled 

- name: 'Reload Firewalld'
  systemd:
    name: firewalld
    state: reloaded            
