---
- name: restart nginx 
  systemd:
    name: nginx
    enabled: yes
    state: restarted

- name: restart php-fpm
  systemd:
    name: php-fpm
    enabled: yes
    state: restarted 

- name: restart iscsi 
  systemd:
    name: iscsid
    enabled: yes
    state: restarted    